// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYVc4ahkUXMHQOeEo1gcV_jDFnjeYaM0A',
    appId: '1:647962445664:web:c1fc5053129efbb6a08005',
    messagingSenderId: '647962445664',
    projectId: 'digi-slip-3cc90',
    authDomain: 'digi-slip-3cc90.firebaseapp.com',
    storageBucket: 'digi-slip-3cc90.firebasestorage.app',
    measurementId: 'G-MJYQPF8B8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOcocbvrZBZGKqeckZHcEbfKiJS9vHjMs',
    appId: '1:647962445664:android:cb7e7d93a3717a20a08005',
    messagingSenderId: '647962445664',
    projectId: 'digi-slip-3cc90',
    storageBucket: 'digi-slip-3cc90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwol-YNIcvHJLu06gvNMXDzRUXom42Gu8',
    appId: '1:647962445664:ios:16401ae1d0bcf3cfa08005',
    messagingSenderId: '647962445664',
    projectId: 'digi-slip-3cc90',
    storageBucket: 'digi-slip-3cc90.firebasestorage.app',
    iosBundleId: 'com.example.digislips',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwol-YNIcvHJLu06gvNMXDzRUXom42Gu8',
    appId: '1:647962445664:ios:16401ae1d0bcf3cfa08005',
    messagingSenderId: '647962445664',
    projectId: 'digi-slip-3cc90',
    storageBucket: 'digi-slip-3cc90.firebasestorage.app',
    iosBundleId: 'com.example.digislips',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYVc4ahkUXMHQOeEo1gcV_jDFnjeYaM0A',
    appId: '1:647962445664:web:c29f9686472b9f6ea08005',
    messagingSenderId: '647962445664',
    projectId: 'digi-slip-3cc90',
    authDomain: 'digi-slip-3cc90.firebaseapp.com',
    storageBucket: 'digi-slip-3cc90.firebasestorage.app',
    measurementId: 'G-QNZ450SBLC',
  );
}
